# Generated by Django 3.2.4 on 2021-10-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geneinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='geneinfo',
            name='gene',
            field=models.TextField(verbose_name='Gene'),
        ),
    ]
