# Generated by Django 3.2.4 on 2021-10-14 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DayNumber',
        ),
        migrations.DeleteModel(
            name='Userip',
        ),
        migrations.DeleteModel(
            name='VisitNumber',
        ),
        migrations.AddField(
            model_name='geneinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
